package app.dqxn.android.pack.essentials.providers

/**
 * Mapping from IANA timezone IDs to ISO 3166-1 alpha-2 country codes.
 *
 * Handles alias resolution via [android.icu.util.TimeZone.getCanonicalID] before lookup. Covers
 * common timezones across Americas, Europe, Asia-Pacific, Africa, and Oceania.
 */
internal object TimezoneCountryMap {

  /**
   * Returns the ISO 3166-1 alpha-2 country code for the given IANA timezone ID, or `null` if
   * unknown.
   *
   * Resolves aliases (e.g., "US/Eastern" -> "America/New_York") before lookup.
   */
  fun getCountryCode(timezoneId: String): String? {
    // Direct lookup first
    TIMEZONE_TO_COUNTRY[timezoneId]?.let { return it }

    // Try canonical ID resolution via ICU
    val canonical = resolveCanonicalId(timezoneId)
    if (canonical != null && canonical != timezoneId) {
      TIMEZONE_TO_COUNTRY[canonical]?.let { return it }
    }

    return null
  }

  private fun resolveCanonicalId(timezoneId: String): String? =
    try {
      android.icu.util.TimeZone.getCanonicalID(timezoneId)
    } catch (_: Exception) {
      null
    }

  /** Common IANA timezone to country code mappings. */
  @Suppress("MaxLineLength")
  private val TIMEZONE_TO_COUNTRY: Map<String, String> =
    mapOf(
      // --- Americas ---
      "America/New_York" to "US",
      "America/Chicago" to "US",
      "America/Denver" to "US",
      "America/Los_Angeles" to "US",
      "America/Anchorage" to "US",
      "America/Phoenix" to "US",
      "America/Indianapolis" to "US",
      "America/Detroit" to "US",
      "America/Boise" to "US",
      "America/Juneau" to "US",
      "America/Adak" to "US",
      "America/Nome" to "US",
      "America/Sitka" to "US",
      "America/Yakutat" to "US",
      "America/Menominee" to "US",
      "America/Kentucky/Louisville" to "US",
      "America/Kentucky/Monticello" to "US",
      "America/Indiana/Indianapolis" to "US",
      "America/Indiana/Knox" to "US",
      "America/Indiana/Marengo" to "US",
      "America/Indiana/Petersburg" to "US",
      "America/Indiana/Tell_City" to "US",
      "America/Indiana/Vevay" to "US",
      "America/Indiana/Vincennes" to "US",
      "America/Indiana/Winamac" to "US",
      "America/North_Dakota/Beulah" to "US",
      "America/North_Dakota/Center" to "US",
      "America/North_Dakota/New_Salem" to "US",
      "Pacific/Honolulu" to "US",
      "America/Toronto" to "CA",
      "America/Vancouver" to "CA",
      "America/Edmonton" to "CA",
      "America/Winnipeg" to "CA",
      "America/Halifax" to "CA",
      "America/St_Johns" to "CA",
      "America/Regina" to "CA",
      "America/Whitehorse" to "CA",
      "America/Yellowknife" to "CA",
      "America/Iqaluit" to "CA",
      "America/Mexico_City" to "MX",
      "America/Tijuana" to "MX",
      "America/Cancun" to "MX",
      "America/Hermosillo" to "MX",
      "America/Monterrey" to "MX",
      "America/Chihuahua" to "MX",
      "America/Merida" to "MX",
      "America/Matamoros" to "MX",
      "America/Sao_Paulo" to "BR",
      "America/Manaus" to "BR",
      "America/Fortaleza" to "BR",
      "America/Recife" to "BR",
      "America/Bahia" to "BR",
      "America/Belem" to "BR",
      "America/Cuiaba" to "BR",
      "America/Argentina/Buenos_Aires" to "AR",
      "America/Argentina/Cordoba" to "AR",
      "America/Argentina/Mendoza" to "AR",
      "America/Bogota" to "CO",
      "America/Lima" to "PE",
      "America/Santiago" to "CL",
      "America/Caracas" to "VE",
      "America/Guayaquil" to "EC",
      "America/La_Paz" to "BO",
      "America/Asuncion" to "PY",
      "America/Montevideo" to "UY",
      "America/Paramaribo" to "SR",
      "America/Cayenne" to "GF",
      "America/Guyana" to "GY",
      // Caribbean
      "America/Havana" to "CU",
      "America/Jamaica" to "JM",
      "America/Port-au-Prince" to "HT",
      "America/Santo_Domingo" to "DO",
      "America/Puerto_Rico" to "PR",
      "America/Nassau" to "BS",
      "America/Cayman" to "KY",
      "America/Barbados" to "BB",
      "America/Martinique" to "MQ",
      "America/Guadeloupe" to "GP",
      "America/Port_of_Spain" to "TT",
      "America/Curacao" to "CW",
      "America/Aruba" to "AW",
      "America/Virgin" to "VI",
      "America/Belize" to "BZ",
      "America/Guatemala" to "GT",
      "America/El_Salvador" to "SV",
      "America/Tegucigalpa" to "HN",
      "America/Managua" to "NI",
      "America/Costa_Rica" to "CR",
      "America/Panama" to "PA",
      // Atlantic
      "Atlantic/Stanley" to "FK",
      "Atlantic/Bermuda" to "BM",
      // US territories
      "Pacific/Pago_Pago" to "AS",
      "Pacific/Guam" to "GU",
      // --- Europe ---
      "Europe/London" to "GB",
      "Europe/Paris" to "FR",
      "Europe/Berlin" to "DE",
      "Europe/Madrid" to "ES",
      "Europe/Rome" to "IT",
      "Europe/Amsterdam" to "NL",
      "Europe/Brussels" to "BE",
      "Europe/Zurich" to "CH",
      "Europe/Vienna" to "AT",
      "Europe/Stockholm" to "SE",
      "Europe/Oslo" to "NO",
      "Europe/Copenhagen" to "DK",
      "Europe/Helsinki" to "FI",
      "Europe/Dublin" to "IE",
      "Europe/Lisbon" to "PT",
      "Europe/Athens" to "GR",
      "Europe/Bucharest" to "RO",
      "Europe/Warsaw" to "PL",
      "Europe/Prague" to "CZ",
      "Europe/Budapest" to "HU",
      "Europe/Belgrade" to "RS",
      "Europe/Sofia" to "BG",
      "Europe/Zagreb" to "HR",
      "Europe/Bratislava" to "SK",
      "Europe/Ljubljana" to "SI",
      "Europe/Tallinn" to "EE",
      "Europe/Riga" to "LV",
      "Europe/Vilnius" to "LT",
      "Europe/Kiev" to "UA",
      "Europe/Kyiv" to "UA",
      "Europe/Moscow" to "RU",
      "Europe/Istanbul" to "TR",
      "Europe/Minsk" to "BY",
      "Europe/Chisinau" to "MD",
      "Europe/Tirane" to "AL",
      "Europe/Skopje" to "MK",
      "Europe/Podgorica" to "ME",
      "Europe/Sarajevo" to "BA",
      "Europe/Luxembourg" to "LU",
      "Europe/Malta" to "MT",
      "Europe/Monaco" to "MC",
      "Europe/Andorra" to "AD",
      "Europe/Gibraltar" to "GI",
      "Atlantic/Reykjavik" to "IS",
      // --- Asia ---
      "Asia/Tokyo" to "JP",
      "Asia/Shanghai" to "CN",
      "Asia/Hong_Kong" to "HK",
      "Asia/Singapore" to "SG",
      "Asia/Seoul" to "KR",
      "Asia/Taipei" to "TW",
      "Asia/Bangkok" to "TH",
      "Asia/Jakarta" to "ID",
      "Asia/Kolkata" to "IN",
      "Asia/Calcutta" to "IN",
      "Asia/Karachi" to "PK",
      "Asia/Dhaka" to "BD",
      "Asia/Colombo" to "LK",
      "Asia/Kathmandu" to "NP",
      "Asia/Manila" to "PH",
      "Asia/Ho_Chi_Minh" to "VN",
      "Asia/Kuala_Lumpur" to "MY",
      "Asia/Phnom_Penh" to "KH",
      "Asia/Vientiane" to "LA",
      "Asia/Yangon" to "MM",
      "Asia/Rangoon" to "MM",
      "Asia/Dubai" to "AE",
      "Asia/Riyadh" to "SA",
      "Asia/Doha" to "QA",
      "Asia/Muscat" to "OM",
      "Asia/Kuwait" to "KW",
      "Asia/Bahrain" to "BH",
      "Asia/Tehran" to "IR",
      "Asia/Baghdad" to "IQ",
      "Asia/Beirut" to "LB",
      "Asia/Damascus" to "SY",
      "Asia/Amman" to "JO",
      "Asia/Jerusalem" to "IL",
      "Asia/Nicosia" to "CY",
      "Asia/Kabul" to "AF",
      "Asia/Tashkent" to "UZ",
      "Asia/Almaty" to "KZ",
      "Asia/Bishkek" to "KG",
      "Asia/Dushanbe" to "TJ",
      "Asia/Ashgabat" to "TM",
      "Asia/Baku" to "AZ",
      "Asia/Tbilisi" to "GE",
      "Asia/Yerevan" to "AM",
      "Asia/Ulaanbaatar" to "MN",
      "Asia/Brunei" to "BN",
      "Asia/Makassar" to "ID",
      "Asia/Jayapura" to "ID",
      // --- Africa ---
      "Africa/Cairo" to "EG",
      "Africa/Lagos" to "NG",
      "Africa/Nairobi" to "KE",
      "Africa/Johannesburg" to "ZA",
      "Africa/Casablanca" to "MA",
      "Africa/Algiers" to "DZ",
      "Africa/Tunis" to "TN",
      "Africa/Tripoli" to "LY",
      "Africa/Accra" to "GH",
      "Africa/Abidjan" to "CI",
      "Africa/Dakar" to "SN",
      "Africa/Dar_es_Salaam" to "TZ",
      "Africa/Addis_Ababa" to "ET",
      "Africa/Kampala" to "UG",
      "Africa/Khartoum" to "SD",
      "Africa/Maputo" to "MZ",
      "Africa/Lusaka" to "ZM",
      "Africa/Harare" to "ZW",
      "Africa/Windhoek" to "NA",
      "Africa/Monrovia" to "LR",
      // --- Oceania ---
      "Australia/Sydney" to "AU",
      "Australia/Melbourne" to "AU",
      "Australia/Brisbane" to "AU",
      "Australia/Perth" to "AU",
      "Australia/Adelaide" to "AU",
      "Australia/Hobart" to "AU",
      "Australia/Darwin" to "AU",
      "Australia/Lord_Howe" to "AU",
      "Pacific/Auckland" to "NZ",
      "Pacific/Chatham" to "NZ",
      "Pacific/Fiji" to "FJ",
      "Pacific/Port_Moresby" to "PG",
      "Pacific/Tongatapu" to "TO",
      "Pacific/Apia" to "WS",
      "Pacific/Noumea" to "NC",
      "Pacific/Majuro" to "MH",
      "Pacific/Palau" to "PW",
      "Pacific/Tarawa" to "KI",
      // --- Common aliases (handled by ICU canonical resolution as well) ---
      "US/Eastern" to "US",
      "US/Central" to "US",
      "US/Mountain" to "US",
      "US/Pacific" to "US",
      "US/Alaska" to "US",
      "US/Hawaii" to "US",
      "US/Arizona" to "US",
      "Canada/Eastern" to "CA",
      "Canada/Central" to "CA",
      "Canada/Mountain" to "CA",
      "Canada/Pacific" to "CA",
      "Canada/Atlantic" to "CA",
      "Canada/Newfoundland" to "CA",
      "Asia/Saigon" to "VN",
      "Asia/Calcutta" to "IN",
      "Asia/Rangoon" to "MM",
    )
}
