package app.dqxn.android.codegen.agentic.generation

import app.dqxn.android.codegen.agentic.model.CommandInfo
import com.google.devtools.ksp.processing.CodeGenerator
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.addOriginatingKSFile
import com.squareup.kotlinpoet.ksp.writeTo

internal class CommandRouterGenerator(
  private val codeGenerator: CodeGenerator,
) {

  fun generate(commands: List<CommandInfo>) {
    val moduleBuilder =
      TypeSpec.classBuilder(MODULE_NAME)
        .addModifiers(KModifier.INTERNAL, KModifier.ABSTRACT)
        .addAnnotation(DAGGER_MODULE)
        .addAnnotation(
          AnnotationSpec.builder(DAGGER_INSTALL_IN)
            .addMember("%T::class", DAGGER_SINGLETON_COMPONENT)
            .build(),
        )

    for (command in commands) {
      moduleBuilder.addOriginatingKSFile(command.originatingFile)

      moduleBuilder.addFunction(
        FunSpec.builder("bind${command.className}")
          .addModifiers(KModifier.INTERNAL, KModifier.ABSTRACT)
          .addAnnotation(DAGGER_BINDS)
          .addAnnotation(DAGGER_INTO_SET)
          .addParameter("impl", command.typeName)
          .returns(COMMAND_HANDLER)
          .build(),
      )
    }

    val fileSpec =
      FileSpec.builder(GENERATED_PACKAGE, MODULE_NAME)
        .addType(moduleBuilder.build())
        .addFileComment("Generated by AgenticProcessor. Do not edit.")
        .build()

    fileSpec.writeTo(codeGenerator, aggregating = false)
  }

  private companion object {
    const val GENERATED_PACKAGE = "app.dqxn.android.core.agentic.generated"
    const val MODULE_NAME = "AgenticHiltModule"

    val DAGGER_MODULE = ClassName("dagger", "Module")
    val DAGGER_BINDS = ClassName("dagger", "Binds")
    val DAGGER_INTO_SET = ClassName("dagger.multibindings", "IntoSet")
    val DAGGER_INSTALL_IN = ClassName("dagger.hilt", "InstallIn")
    val DAGGER_SINGLETON_COMPONENT = ClassName("dagger.hilt.components", "SingletonComponent")
    val COMMAND_HANDLER = ClassName("app.dqxn.android.core.agentic", "CommandHandler")
  }
}
