package app.dqxn.android.codegen.agentic.generation

import app.dqxn.android.codegen.agentic.model.CommandInfo
import com.google.devtools.ksp.processing.CodeGenerator
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import com.squareup.kotlinpoet.ksp.addOriginatingKSFile
import com.squareup.kotlinpoet.ksp.writeTo

internal class SchemaGenerator(
  private val codeGenerator: CodeGenerator,
) {

  fun generate(commands: List<CommandInfo>) {
    val entryType =
      TypeSpec.classBuilder(ENTRY_NAME)
        .addModifiers(KModifier.DATA)
        .primaryConstructor(
          FunSpec.constructorBuilder()
            .addParameter("name", String::class)
            .addParameter("description", String::class)
            .addParameter("category", String::class)
            .build(),
        )
        .addProperty(
          PropertySpec.builder("name", String::class).initializer("name").build(),
        )
        .addProperty(
          PropertySpec.builder("description", String::class).initializer("description").build(),
        )
        .addProperty(
          PropertySpec.builder("category", String::class).initializer("category").build(),
        )
        .build()

    val entryClassName = ClassName(GENERATED_PACKAGE, OBJECT_NAME, ENTRY_NAME)

    val commandsInitializer = CodeBlock.builder().add("listOf(\n").indent()

    commands.forEachIndexed { index, command ->
      commandsInitializer.add(
        "%T(name = %S, description = %S, category = %S)",
        entryClassName,
        command.name,
        command.description,
        command.category,
      )
      if (index < commands.size - 1) {
        commandsInitializer.add(",\n")
      } else {
        commandsInitializer.add(",\n")
      }
    }

    commandsInitializer.unindent().add(")")

    val commandsProperty =
      PropertySpec.builder(
          "commands",
          List::class.asClassName().parameterizedBy(entryClassName),
        )
        .initializer(commandsInitializer.build())
        .build()

    val objectBuilder =
      TypeSpec.objectBuilder(OBJECT_NAME).addType(entryType).addProperty(commandsProperty)

    for (command in commands) {
      objectBuilder.addOriginatingKSFile(command.originatingFile)
    }

    val fileSpec =
      FileSpec.builder(GENERATED_PACKAGE, OBJECT_NAME)
        .addType(objectBuilder.build())
        .addFileComment("Generated by AgenticProcessor. Do not edit.")
        .build()

    fileSpec.writeTo(codeGenerator, aggregating = true)
  }

  private companion object {
    const val GENERATED_PACKAGE = "app.dqxn.android.core.agentic.generated"
    const val OBJECT_NAME = "GeneratedCommandSchema"
    const val ENTRY_NAME = "CommandSchemaEntry"
  }
}
